ct-key: "../certificate-transparency/test/testdata/ct-server-key-public.pem"
ct-url: "http://107.178.246.112"
vrf:    "testdata/vrf-pubkey.pem"
domain: "example.com"
kt-key: "testdata/server.crt"
kt-sig: "testdata/p256-pubkey.pem"
kt-url: "localhost:5003"
client-secret: "testdata/client_secret.json"
